# Generated by Django 3.1 on 2020-09-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0002_auto_20200930_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyresult',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default='2012-09-04 06:00:00.000000-08:00'),
            preserve_default=False,
        ),
    ]
