# Generated by Django 3.1 on 2020-09-30 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0003_dailyresult_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyresult',
            name='datetime',
        ),
    ]
