# Generated by Django 3.1 on 2020-10-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0004_remove_dailyresult_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyresult',
            name='isPinned',
            field=models.BooleanField(default=False),
        ),
    ]
