# Generated by Django 3.1 on 2020-10-09 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0006_dailyresult_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyresult',
            name='description',
        ),
    ]
