# Generated by Django 3.1 on 2020-11-02 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201102_2050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='active_time',
            new_name='How_long_can_you_be_active_on_the_server_everyday',
        ),
    ]
