# Generated by Django 3.1 on 2020-10-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyResult',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('title_1', models.CharField(max_length=255)),
                ('desc_1', models.TextField()),
                ('author_1', models.CharField(max_length=13)),
                ('slug_1', models.CharField(max_length=130)),
                ('timeStamp1', models.DateTimeField(blank=True)),
            ],
        ),
    ]
