# Generated by Django 3.1 on 2020-10-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekly', '0002_remove_weeklyresult_timestamp1'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyresult',
            name='timeStamp1',
            field=models.DateTimeField(blank=True, default='2012-09-04 06:00:00.000000-08:00'),
            preserve_default=False,
        ),
    ]
