# Generated by Django 3.1 on 2020-10-01 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weekly', '0003_weeklyresult_timestamp1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weeklyresult',
            old_name='author_1',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='weeklyresult',
            old_name='desc_1',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='weeklyresult',
            old_name='slug_1',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='weeklyresult',
            old_name='s_no',
            new_name='sno',
        ),
        migrations.RenameField(
            model_name='weeklyresult',
            old_name='timeStamp1',
            new_name='timeStamp',
        ),
        migrations.RenameField(
            model_name='weeklyresult',
            old_name='title_1',
            new_name='title',
        ),
    ]
