# Generated by Django 3.1 on 2020-10-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekly', '0004_auto_20201001_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyresult',
            name='isPinned',
            field=models.BooleanField(default=False),
        ),
    ]
